mode: term
base_path: /home/ubuntu/mylrz/atsc-experiments/DATA/SEMEVAL-14-LAP
glove_path: /home/ubuntu/mylrz/atsc-experiments/DATA/glove.840B.300d.txt
sentiment_path: /home/ubuntu/mylrz/atsc-experiments/DATA/MAMS/sentiment_dict.json
lowercase: True
max_vocab_size: None
min_vocab_freq: 0
train_set: 1 # 1 for training mode, 0 for test mode
rand_state: 1 # 1,2,3,4,5  # select train/val sets for semeval data, otherwise 0
patience: 5
seed: 1 #1,2,3,4,5 for reproducibility
aspect_term_model:
  type: bert_capsnet
  recurrent_capsnet:
    embed_size: 300
    dropout: 0.5
    num_layers: 2
    capsule_size: 300
    bidirectional: True
    optimizer: adam
    batch_size: 64
    learning_rate: 0.0003
    weight_decay: 0
    num_epoches: 20
    gpu: 0
  bert_capsnet:
    bert_size: 768
    capsule_size: 300
    dropout: 0.1
    optimizer: adam
    batch_size: 32
    learning_rate: 0.00002
    weight_decay: 0
    num_epoches: 5
    gpu: 0
aspect_category_model:
  type: recurrent_capsnet
  recurrent_capsnet:
    embed_size: 300
    dropout: 0.5
    num_layers: 2
    capsule_size: 300
    bidirectional: True
    optimizer: adam
    batch_size: 64
    learning_rate: 0.0003
    weight_decay: 0
    num_epoches: 20
    gpu: 0
  bert_capsnet:
    bert_size: 768
    capsule_size: 300
    dropout: 0.1
    optimizer: adam
    batch_size: 32
    learning_rate: 0.00003
    weight_decay: 0
    num_epoches: 5
    gpu: 0
